export enum CanvasActions {
  INITIATE_MOUSE_EVENT = "CANVAS/INITIATE_MOUSE_EVENT",
  DRAW_IN_CANVAS = "CANVAS/DRAW_IN_CANVAS",

  READ_CANVAS_DRAWINGS = "CANVAS/READ_CANVAS_DRAWING",
  STOP_LISTEN_TO_FIREBASE_DRAWING = "CANVAS/STOP_LISTEN_TO_FIREBASE_DRAWING",
  ERROR_READ_CANVAS_DRAWING = "CANVAS/ERROR_READ_CANVAS_DRAWING",

  CHANGE_PEN_COLOR = "CANVAS/CHANGE_PEN_COLOR",
  CHANGE_PEN_SIZE = "CANVAS/CHANGE_PEN_SIZE",
}
