export enum UserActions {
  LOGIN_WITH_GOOGLE_REQ = "USER/LOGIN_WITH_GOOGLE_REQ",
  LOGIN_WITH_GOOGLE_OK = "USER/LOGIN_WITH_GOOGLE_OK",
  LOGIN_WITH_GOOGLE_ERR = "USER/LOGIN_WITH_GOOGLE_ERR",
  CLEAR_STATE_LOGIN_WITH_GOOGLE = "USER/CLEAR_STATE_LOGIN_WITH_GOOGLE",

  LISTEN_ON_USER_CHANGES = "USER/LISTEN_ON_USER_CHANGES",

  GET_USER_PROFILE_REQ = "USER/GET_USER_PROFILE_REQ",
  GET_USER_PROFILE_OK = "USER/GET_USER_PROFILE_OK",
  GET_USER_PROFILE_ERR = "USER/GET_USER_PROFILE_ERR",
  CLEAR_STATE_GET_USER_PROFILE = "USER/CLEAR_STATE_GET_USER_PROFILE",
}
