export enum UserActions {
  LOGIN_WITH_GOOGLE_REQ = "USER/LOGIN_WITH_GOOGLE_REQ",
  LOGIN_WITH_GOOGLE_OK = "USER/LOGIN_WITH_GOOGLE_OK",
  LOGIN_WITH_GOOGLE_ERR = "USER/LOGIN_WITH_GOOGLE_ERR",
  CLEAR_STATE_LOGIN_WITH_GOOGLE = "USER/CLEAR_STATE_LOGIN_WITH_GOOGLE",

  LISTEN_ON_USER_CHANGES = "USER/LISTEN_ON_USER_CHANGES",
}
